apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ftzm-nginx-flask
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ftzm-nginx-flask-pod
    spec:
      containers:
        - name: ftzm-nginx
          image: ftzm:v1
          ports:
          - containerPort: 80
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: flask-secrets
                  key: flask_secret_key
            - name: BASIC_AUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: flask-secrets
                  key: basic_auth_username
            - name: BASIC_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: flask-secrets
                  key: basic_auth_password
            - name: POSTGRES_PW
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: postgrespw
